### PR TITLE
docs: switch to crossplane-system namespace everywhere for consistency

### PR DESCRIPTION
**Pull request by phisco**
### Description of your changes

Switching all occurrences of `upbound-system` namespace back to `crossplane-namespace`.

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

**Comment by bobh66** [comment]
> crossplane-system is not created anymore, 

Since when?  Community crossplane deploys into crossplane-system, and that should remain the default for all non-Upbound providers.

upbound-system is only used for downstream uxp and should not be referenced in anything upstream of uxp

**Comment by turkenh** [comment]
> Since when? Community crossplane deploys into crossplane-system, and that should remain the default for all non-Upbound providers.

> upbound-system is only used for downstream uxp and should not be referenced in anything upstream of uxp

Agreed. 

This was changed for local development recently for integrating uptest for e2e testing: https://github.com/crossplane-contrib/provider-kubernetes/pull/118

But, I believe we should rather configure uptest to use `crossplane-system` instead.

**Comment by phisco** [comment]
good point @bobh66, totally agree, my main concern was about consistency and the procedure in the README properly working. I switched everything to `crossplane-system` and tomorrow we'll fix the build sub module to properly handle CROSSPLANE_NAMESPACE 👍

**Review by turkenh — APPROVED** [review]
Thanks @phisco 🙌

**Comment by phisco** [comment]
Just noticed the cleanup `make local.down` in the README doesn't work for me.
I'm not sure which would be the correct target to use for that though 🤔 
CC @turkenh

**Comment by turkenh** [comment]
@phisco I assume it should be updated as `make controlplane.down`.

**Comment by phisco** [comment]
pushed the change, it works fine now, totally missed that target, thanks @turkenh!

**Pull request merged**
