### PR TITLE
Allow Azure Workload identity authentication

### PR DESCRIPTION
**Pull request by patst**
### Description of your changes

We want to use Azure Workload Identity to provision resources with the Kubernetes provider.,
At the moment only Azure Service Principal authentication is possible (see https://github.com/crossplane-contrib/provider-kubernetes/blob/47afbb7fbea2e8db7c430d1cd8d115644999086f/apis/v1alpha1/types.go#L53 )

Details about Azure workload Identity: https://azure.github.io/kubelogin/concepts/login-modes/workloadidentity.html#workload-identity 

this is an addition to https://github.com/crossplane-contrib/provider-kubernetes/pull/170 done by @haarchri 

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable test` to ensure this PR is ready for review.
 ( there is one finding: `internal/clients/azure/azure.go:30:1: cyclomatic complexity 11 of func `WrapRESTConfig` is high (> 10) `, any suggestion how to fix it? For me it only reduces readability to split up the function)

### How has this code been tested

Deployed it in a AKS Cluster and checked if I can access the cluster and provision resources.

Example configuration:
```yaml
apiVersion: kubernetes.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: kubernetes-provider
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: cluster-config
      key: kubeconfig
  identity:
    type: AzureWorkloadIdentityCredentials
    source: Secret
    secretRef:
      name: azure-wli-credentials
      namespace: crossplane-system
      key: credentials.json
---
apiVersion: v1
kind: Secret
metadata:
  name: azure-wli-credentials
  namespace: crossplane-system
stringData:
  # serverId hardcoded to AKS ID, see https://azure.github.io/kubelogin/concepts/aks.html#azure-kubernetes-service-aad-server
  credentials.json: |
    {
      "tenantId": "<aad-tenant-id>",
      "serverId": "6dae42f8-4368-4678-94ff-3960e28e3630",
      "clientId": "<client-id>",
      "federatedTokenFile": "/var/run/secrets/azure/tokens/azure-identity-token",
      "authorityHost": "https://login.microsoftonline.com/"
     }

```

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

**Comment by cychiang** [comment]
This is great, and wondering when would be possible to merge it?

**Comment by turkenh** [comment]
@patst, thanks for the PR, and sorry for being late here. 

Would you mind rebasing your PR, so that we can move it forward?

**Comment by patst** [comment]
> @patst, thanks for the PR, and sorry for being late here.
> 
> Would you mind rebasing your PR, so that we can move it forward?

@turkenh  great you found the time. We are using the self-build version in production since a few months and are very happy.

I rebased the changes and hopefully was able to resolve the merge conflicts correct

**Review by turkenh — APPROVED** [review]
Looking good, thanks for your contribution @patst 🙌

**Comment by turkenh** [comment]
@patst, I just merged https://github.com/crossplane-contrib/provider-kubernetes/pull/225, which is also touching similar codepaths as your PR. Here is an image build from the latest main, including both PRs: `xpkg.upbound.io/crossplane-contrib/provider-kubernetes:v0.14.0-rc0.38.gb6e342f`

It would be great if you could test/validate this image on your environment to make sure nothing is broken before cutting a release 🙏

**Comment by patst** [comment]
> @patst, I just merged #225, which is also touching similar codepaths as your PR. Here is an image build from the latest main, including both PRs: `xpkg.upbound.io/crossplane-contrib/provider-kubernetes:v0.14.0-rc0.38.gb6e342f`
> 
> It would be great if you could test/validate this image on your environment to make sure nothing is broken before cutting a release 🙏

thanks for merging it.
I just tested `xpkg.upbound.io/crossplane-contrib/provider-kubernetes:v0.14.0-rc0.38.gb6e342f` in our sandbox environment and it worked fine.

**Comment by ebberholmes** [comment]
Thanks for this feature! I am having issues making it work. 
Can you elaborate on the `federatedTokenFile` - should I mount a secret into the kubernetes-provider pod on the /var/run/secrets/... path?
What must the content of the `federatedTokenFile` be?
Thanks!

**Comment by jlemoingora** [comment]
@ebberholmes Hello did you get an answer about the federatedTokenFile ? i'm not able to use this feature i got this error : 

failed to get API group resources:  unable to retrieve the complete list of server APIs: v1: Get \"https://xxxx/api/v1\": cannot get azure token: failed to acquire token. open /var/run/secrets/azure/tokens/azure-identity-token: no such file or directory

**Comment by ebberholmes** [comment]
@jlemoingora I didn't get around to it yet. What is needed though, is a federated credential on a managed identity (UMI) for the AKS cluster. Then a Service Account (SA) that maps to the UMI, and then I think the provider-kubernetes pod has to somehow use that SA. When the SA is used, the default location for the credentials is that /var/run/... dir. Maybe there is a providerconfig or similar, but I haven't tried it yet.

**Pull request merged**
